language: csharp
dotnet: 2.2
solution: src/HelloWorld.sln

script:
  - dotnet restore
  - dotnet publish -c Release -r win-x64 --self-contained true

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: src/HelloWorld/bin/Release/netcoreapp2.2/win-x64/publish/**/*
  on:
    tags: true